BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no

EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

#薙刀式
UNICODE_ENABLE = yes
#SRC +=    naginata_v14.c
EXTRAFLAGS += -flto
